// Package images is a pure-Go (cgo-free) image-processing library in the style
// of scikit-image, built on the Go standard library's image, image/color,
// image/png and image/jpeg packages.
//
// Unlike the established options in the Ruby world — ruby-vips (libvips) and
// RMagick (ImageMagick) — and unlike cgo-backed Go wrappers, this library has
// no native C dependency: it is CGO=0 and builds and runs identically on every
// Go target. That makes it trivially cross-compilable and embeddable (for
// example inside go-embedded-ruby), at the cost — for now — of the hand-tuned
// SIMD that libvips/ImageMagick rely on. A later phase will close that gap with
// SIMD kernels generated by go-asmgen across the six supported 64-bit targets.
// See docs/plan-images.md for the roadmap and an honest comparison with the
// existing pure-Go libraries (bild, disintegration/imaging).
//
// Operations are pure functions: each takes an image and returns a freshly
// allocated *image.RGBA, never mutating its input. Use ToRGBA to convert an
// arbitrary image.Image to the *image.RGBA the operations consume, and the I/O
// helpers (Load, Save, Decode, Encode) for PNG and JPEG.
//
// Phase 0 implements Grayscale, Invert, Resize (nearest-neighbour and
// bilinear), Convolve (arbitrary odd-sized kernels with edge clamping),
// GaussianBlur (separable), AdjustBrightness and AdjustContrast. Phase 1 adds
// Sobel edge detection: Sobel (gradient magnitude), SobelX and SobelY
// (directional responses).
package images
