// Package kernels holds the per-pixel inner loops used by the public image
// operations. Keeping the hot loops isolated here lets callers depend on a
// stable, narrow surface while the implementation evolves.
//
// Every loop in this package is currently scalar, pure Go, and CGO-free so the
// library builds and runs identically on every Go target. The pixel layout it
// assumes is the one used by image.RGBA: a tightly packed, row-major slice of
// 8-bit R, G, B, A components. That regular layout is deliberate: it is exactly
// the shape that maps onto vector registers, so a future phase can drop in SIMD
// kernels generated by go-asmgen (https://github.com/go-asmgen) for the six
// supported 64-bit Go targets (amd64, arm64, riscv64, loong64, ppc64le, s390x)
// behind these same function signatures without touching the public API.
package kernels

import "math"

// ClampByte rounds and clamps a floating-point intensity to the [0, 255] range
// representable by a single 8-bit channel.
func ClampByte(v float64) uint8 {
	if v <= 0 {
		return 0
	}
	if v >= 255 {
		return 255
	}
	return uint8(v + 0.5)
}

// Grayscale converts every pixel of src to its luminance-weighted gray value,
// writing the result into dst. The alpha channel is preserved. The Rec. 601
// luma coefficients (0.299, 0.587, 0.114) are used. dst and src must have the
// same length, a multiple of four.
func Grayscale(dst, src []uint8) {
	for i := 0; i < len(src); i += 4 {
		r := float64(src[i])
		g := float64(src[i+1])
		b := float64(src[i+2])
		y := ClampByte(0.299*r + 0.587*g + 0.114*b)
		dst[i] = y
		dst[i+1] = y
		dst[i+2] = y
		dst[i+3] = src[i+3]
	}
}

// Invert negates the R, G and B channels of every pixel of src into dst,
// leaving alpha untouched. dst and src must have the same length, a multiple of
// four.
func Invert(dst, src []uint8) {
	for i := 0; i < len(src); i += 4 {
		dst[i] = 255 - src[i]
		dst[i+1] = 255 - src[i+1]
		dst[i+2] = 255 - src[i+2]
		dst[i+3] = src[i+3]
	}
}

// AdjustBrightness adds delta to the R, G and B channels of every pixel of src
// into dst, clamping to [0, 255]. Alpha is preserved.
func AdjustBrightness(dst, src []uint8, delta float64) {
	for i := 0; i < len(src); i += 4 {
		dst[i] = ClampByte(float64(src[i]) + delta)
		dst[i+1] = ClampByte(float64(src[i+1]) + delta)
		dst[i+2] = ClampByte(float64(src[i+2]) + delta)
		dst[i+3] = src[i+3]
	}
}

// AdjustContrast scales the R, G and B channels of every pixel of src about the
// mid-point (128) by factor, into dst, clamping to [0, 255]. Alpha is
// preserved. A factor of 1 leaves the image unchanged.
func AdjustContrast(dst, src []uint8, factor float64) {
	for i := 0; i < len(src); i += 4 {
		dst[i] = ClampByte((float64(src[i])-128)*factor + 128)
		dst[i+1] = ClampByte((float64(src[i+1])-128)*factor + 128)
		dst[i+2] = ClampByte((float64(src[i+2])-128)*factor + 128)
		dst[i+3] = src[i+3]
	}
}

// inRangeSpan returns the half-open span [lo,hi) of destination indices x in
// [0,width) for which the shifted source index x+t lies in range [0,width). For
// t < 0 the leftmost -t columns read before the start; for t > 0 the rightmost t
// read past the end; those border columns are handled by clamping. The result is
// itself clamped to [0,width] with lo <= hi, so a shift larger than the line
// width (|t| >= width, where every column is a border) yields an empty span.
func inRangeSpan(t, width int) (lo, hi int) {
	if t < 0 {
		lo = -t
		if lo > width { // shift larger than the line: every column is a border
			lo = width
		}
		return lo, width
	}
	hi = width - t
	if hi < 0 {
		hi = 0
	}
	return 0, hi
}

// clampIndex clamps i to [0, n).
func clampIndex(i, n int) int {
	if i < 0 {
		return 0
	}
	if i >= n {
		return n - 1
	}
	return i
}

// Convolve applies an arbitrary kernel of odd dimensions to src and writes the
// result into dst. src and dst are RGBA pixel slices of width*height pixels;
// kernel is a row-major (kh*kw) slice of weights. Edges use clamp-to-edge
// addressing. The R, G and B channels are convolved; alpha is copied from the
// corresponding source pixel unchanged.
func Convolve(dst, src []uint8, width, height int, kernel []float64, kw, kh int) {
	halfW := kw / 2
	halfH := kh / 2
	for y := 0; y < height; y++ {
		for x := 0; x < width; x++ {
			var sr, sg, sb float64
			for ky := 0; ky < kh; ky++ {
				sy := clampIndex(y+ky-halfH, height)
				for kx := 0; kx < kw; kx++ {
					sx := clampIndex(x+kx-halfW, width)
					w := kernel[ky*kw+kx]
					si := (sy*width + sx) * 4
					sr += w * float64(src[si])
					sg += w * float64(src[si+1])
					sb += w * float64(src[si+2])
				}
			}
			di := (y*width + x) * 4
			dst[di] = ClampByte(sr)
			dst[di+1] = ClampByte(sg)
			dst[di+2] = ClampByte(sb)
			dst[di+3] = src[di+3]
		}
	}
}

// GaussianKernel1D returns a normalised one-dimensional Gaussian kernel for the
// given sigma, which must be positive. The radius is ceil(3*sigma) (always at
// least 1 for sigma > 0), so the kernel length is 2*radius+1 (always odd).
func GaussianKernel1D(sigma float64) []float64 {
	radius := int(math.Ceil(3 * sigma))
	size := 2*radius + 1
	k := make([]float64, size)
	var sum float64
	twoSigmaSq := 2 * sigma * sigma
	for i := -radius; i <= radius; i++ {
		v := math.Exp(-float64(i*i) / twoSigmaSq)
		k[i+radius] = v
		sum += v
	}
	for i := range k {
		k[i] /= sum
	}
	return k
}

// ConvolveSeparable applies a one-dimensional kernel k as a horizontal pass
// followed by a vertical pass (a separable convolution), writing the result
// into dst via the scratch buffer tmp. src, tmp and dst are RGBA pixel slices
// of width*height pixels and must be distinct. Edges use clamp-to-edge
// addressing; alpha is preserved.
//
// The implementation deinterleaves the R, G and B channels into contiguous
// float64 planes so each pass is a multiply-accumulate over a flat array — the
// shape the SIMD axpy kernel (dst[i] += w*src[i]) vectorises — and fans the
// independent rows/columns out across cores above ParThreshold. The intermediate
// result is still rounded to bytes between the two passes (tmp), exactly as the
// former scalar implementation did, so the numeric output is unchanged. The
// per-tap accumulation order (kernel tap by kernel tap, over a whole line) is
// the same order the scalar oracle uses, so on amd64-v1 and arm64 the result is
// bit-identical to the scalar reference and the box-blur/Gaussian correctness
// tests continue to hold.
func ConvolveSeparable(dst, tmp, src []uint8, width, height int, k []float64) {
	radius := len(k) / 2
	n := width * height
	// Horizontal pass: src bytes -> per-channel byte planes (clamped), carried
	// in tmp as RGBA so alpha rides along unchanged.
	hr := make([]float64, n)
	hg := make([]float64, n)
	hb := make([]float64, n)
	forLines(height, width, func(lo, hi int) {
		convH(hr, hg, hb, src, width, lo, hi, k, radius)
	})
	// Round the horizontal result into tmp (bytes), copying alpha from src.
	forLines(height, width, func(lo, hi int) {
		for i := lo * width; i < hi*width; i++ {
			di := i * 4
			tmp[di] = ClampByte(hr[i])
			tmp[di+1] = ClampByte(hg[i])
			tmp[di+2] = ClampByte(hb[i])
			tmp[di+3] = src[di+3]
		}
	})
	// Vertical pass: tmp bytes -> per-channel float planes -> dst bytes.
	vr := make([]float64, n)
	vg := make([]float64, n)
	vb := make([]float64, n)
	forLines(height, width, func(lo, hi int) {
		convV(vr, vg, vb, tmp, width, height, lo, hi, k, radius)
	})
	forLines(height, width, func(lo, hi int) {
		for i := lo * width; i < hi*width; i++ {
			di := i * 4
			dst[di] = ClampByte(vr[i])
			dst[di+1] = ClampByte(vg[i])
			dst[di+2] = ClampByte(vb[i])
			dst[di+3] = tmp[di+3]
		}
	})
}

// convH runs the horizontal convolution for rows [lo,hi) of an RGBA image,
// writing per-channel float accumulators into hr/hg/hb. For each kernel tap the
// in-range columns are accumulated as a contiguous SIMD axpy over the row; the
// few columns whose source index is clamped at a border are handled with a
// scalar add, so the result matches the scalar oracle exactly.
func convH(hr, hg, hb []float64, src []uint8, width, lo, hi int, k []float64, radius int) {
	rr := make([]float64, width)
	rg := make([]float64, width)
	rb := make([]float64, width)
	for y := lo; y < hi; y++ {
		base := y * width * 4
		// Deinterleave this row's R, G, B into contiguous float scratch.
		for x := 0; x < width; x++ {
			p := base + x*4
			rr[x] = float64(src[p])
			rg[x] = float64(src[p+1])
			rb[x] = float64(src[p+2])
		}
		out := y * width
		ar := hr[out : out+width]
		ag := hg[out : out+width]
		ab := hb[out : out+width]
		for i := range ar {
			ar[i], ag[i], ab[i] = 0, 0, 0
		}
		for t := -radius; t <= radius; t++ {
			w := k[t+radius]
			// Destination column x reads source column x+t. Over the in-range
			// span the read is a contiguous shift, so axpy applies; the clamped
			// border columns are added scalar.
			loX, hiX := inRangeSpan(t, width)
			// Border-clamped left columns (x+t < 0 -> src col 0).
			for x := 0; x < loX; x++ {
				ar[x] += w * rr[0]
				ag[x] += w * rg[0]
				ab[x] += w * rb[0]
			}
			// Border-clamped right columns (x+t >= width -> src col width-1).
			for x := hiX; x < width; x++ {
				ar[x] += w * rr[width-1]
				ag[x] += w * rg[width-1]
				ab[x] += w * rb[width-1]
			}
			if hiX > loX {
				axpy(ar[loX:hiX], rr[loX+t:hiX+t], w)
				axpy(ag[loX:hiX], rg[loX+t:hiX+t], w)
				axpy(ab[loX:hiX], rb[loX+t:hiX+t], w)
			}
		}
	}
}

// convV runs the vertical convolution for output rows [lo,hi), reading the
// byte-rounded horizontal result from the RGBA buffer mid and writing
// per-channel float accumulators into vr/vg/vb. Each kernel tap adds w times a
// whole (clamped) source row — a contiguous SIMD axpy of width elements — so the
// border handling collapses to choosing which source row to read.
func convV(vr, vg, vb []float64, mid []uint8, width, height, lo, hi int, k []float64, radius int) {
	rowR := make([]float64, width)
	rowG := make([]float64, width)
	rowB := make([]float64, width)
	for y := lo; y < hi; y++ {
		out := y * width
		ar := vr[out : out+width]
		ag := vg[out : out+width]
		ab := vb[out : out+width]
		for i := range ar {
			ar[i], ag[i], ab[i] = 0, 0, 0
		}
		for t := -radius; t <= radius; t++ {
			w := k[t+radius]
			sy := clampIndex(y+t, height)
			base := sy * width * 4
			for x := 0; x < width; x++ {
				p := base + x*4
				rowR[x] = float64(mid[p])
				rowG[x] = float64(mid[p+1])
				rowB[x] = float64(mid[p+2])
			}
			axpy(ar, rowR, w)
			axpy(ag, rowG, w)
			axpy(ab, rowB, w)
		}
	}
}

// BoxBlur applies a (2*radius+1) by (2*radius+1) averaging filter to src,
// writing the result into dst. It is implemented as a separable pair of
// one-dimensional moving-average passes, each maintaining a running window sum
// so the per-pixel cost is O(1) in the radius rather than O(radius). The
// intermediate result is carried in floating point (one value per channel per
// pixel) so the two passes compose to the exact two-dimensional mean, with a
// single rounding at the end — matching scipy.ndimage.uniform_filter (which is
// likewise separable and stays in float). Edges use clamp-to-edge addressing
// (uniform_filter's mode="nearest"); the R, G and B channels are averaged and
// alpha is preserved. dst and src are RGBA pixel slices of width*height pixels
// and must be distinct. radius must be >= 1.
func BoxBlur(dst, src []uint8, width, height, radius int) {
	win := 2*radius + 1
	inv := 1.0 / float64(win)
	// mid holds the horizontal-pass result as floats: three channels per pixel,
	// already divided by the window width, ready for the vertical pass.
	mid := make([]float64, width*height*3)
	// Horizontal pass: src bytes -> mid floats (rows independent, tiled).
	forLines(height, width, func(lo, hi int) {
		for y := lo; y < hi; y++ {
			boxBlurH(mid, src, y*width*3, y*width*4, width, radius, inv)
		}
	})
	// Vertical pass: mid floats -> dst bytes (columns independent, tiled).
	forLines(width, height, func(lo, hi int) {
		for x := lo; x < hi; x++ {
			boxBlurV(dst, mid, src, x, width, height, radius, inv)
		}
	})
}

// boxBlurH runs the horizontal moving-average over one row of `n` pixels read
// from src (RGBA bytes, base byte offset srcBase) and writes the per-channel
// windowed means as floats into mid (3 floats per pixel, base index midBase).
// Samples beyond the row ends are clamped to the first/last pixel.
func boxBlurH(mid []float64, src []uint8, midBase, srcBase, n, radius int, inv float64) {
	sample := func(i int) int {
		if i < 0 {
			i = 0
		} else if i >= n {
			i = n - 1
		}
		return srcBase + i*4
	}
	var sr, sg, sb float64
	for i := -radius; i <= radius; i++ {
		si := sample(i)
		sr += float64(src[si])
		sg += float64(src[si+1])
		sb += float64(src[si+2])
	}
	for i := 0; i < n; i++ {
		mi := midBase + i*3
		mid[mi] = sr * inv
		mid[mi+1] = sg * inv
		mid[mi+2] = sb * inv
		lo := sample(i - radius)
		hi := sample(i + radius + 1)
		sr += float64(src[hi]) - float64(src[lo])
		sg += float64(src[hi+1]) - float64(src[lo+1])
		sb += float64(src[hi+2]) - float64(src[lo+2])
	}
}

// boxBlurV runs the vertical moving-average over one column x of `height`
// samples taken from the float plane mid (3 floats per pixel, row stride
// width*3), writing the rounded R, G, B into dst (RGBA bytes) and copying alpha
// from src. Samples beyond the column ends are clamped to the first/last row.
func boxBlurV(dst []uint8, mid []float64, src []uint8, x, width, height, radius int, inv float64) {
	stride := width * 3
	base := x * 3
	sample := func(i int) int {
		if i < 0 {
			i = 0
		} else if i >= height {
			i = height - 1
		}
		return base + i*stride
	}
	var sr, sg, sb float64
	for i := -radius; i <= radius; i++ {
		si := sample(i)
		sr += mid[si]
		sg += mid[si+1]
		sb += mid[si+2]
	}
	for i := 0; i < height; i++ {
		di := (i*width + x) * 4
		dst[di] = ClampByte(sr * inv)
		dst[di+1] = ClampByte(sg * inv)
		dst[di+2] = ClampByte(sb * inv)
		dst[di+3] = src[di+3]
		lo := sample(i - radius)
		hi := sample(i + radius + 1)
		sr += mid[hi] - mid[lo]
		sg += mid[hi+1] - mid[lo+1]
		sb += mid[hi+2] - mid[lo+2]
	}
}

// lumaPlane converts the width*height RGBA image src to a tightly packed plane
// of Rec. 601 luminance values (one float64 per pixel, matching the Grayscale
// coefficients 0.299, 0.587, 0.114). Computing the plane once keeps each source
// pixel's luminance from being recomputed for every kernel tap that reads it.
func lumaPlane(src []uint8, width, height int) []float64 {
	lum := make([]float64, width*height)
	for i := range lum {
		j := i * 4
		lum[i] = 0.299*float64(src[j]) + 0.587*float64(src[j+1]) + 0.114*float64(src[j+2])
	}
	return lum
}

// GaussianPlane returns the width*height luminance plane of src (Rec. 601),
// smoothed by a separable Gaussian of standard deviation sigma with
// clamp-to-edge borders. It is the pre-smoothing step of Canny: the smoothing
// runs on the single luminance channel (as skimage.feature.canny does) rather
// than on the three colour channels. The result stays in float64 [0,255] so the
// subsequent Sobel gradients are computed without an intermediate byte rounding.
func GaussianPlane(src []uint8, width, height int, sigma float64) []float64 {
	lum := lumaPlane(src, width, height)
	k := GaussianKernel1D(sigma)
	radius := len(k) / 2
	n := width * height
	tmp := make([]float64, n)
	// Horizontal pass: lum -> tmp.
	forLines(height, width, func(lo, hi int) {
		for y := lo; y < hi; y++ {
			row := y * width
			for x := 0; x < width; x++ {
				var s float64
				for t := -radius; t <= radius; t++ {
					s += k[t+radius] * lum[row+clampIndex(x+t, width)]
				}
				tmp[row+x] = s
			}
		}
	})
	// Vertical pass: tmp -> out.
	out := make([]float64, n)
	forLines(height, width, func(lo, hi int) {
		for y := lo; y < hi; y++ {
			for x := 0; x < width; x++ {
				var s float64
				for t := -radius; t <= radius; t++ {
					s += k[t+radius] * tmp[clampIndex(y+t, height)*width+x]
				}
				out[y*width+x] = s
			}
		}
	})
	return out
}

// sobelGradients computes, for the pixel at (x, y) of a width*height luminance
// plane lum, the horizontal (gx) and vertical (gy) Sobel responses, using
// clamp-to-edge addressing at the borders.
//
// The Sobel kernels are
//
//	gx = [-1 0 1; -2 0 2; -1 0 1]   gy = [-1 -2 -1; 0 0 0; 1 2 1]
//
// fully unrolled below: with both kernels' middle column (gx) and middle row
// (gy) being zero, only six taps contribute to each gradient.
func sobelGradients(lum []float64, width, height, x, y int) (gx, gy float64) {
	x0 := clampIndex(x-1, width)
	x1 := clampIndex(x+1, width)
	y0 := clampIndex(y-1, height)
	y1 := clampIndex(y+1, height)
	tl := lum[y0*width+x0]
	tc := lum[y0*width+x]
	tr := lum[y0*width+x1]
	ml := lum[y*width+x0]
	mr := lum[y*width+x1]
	bl := lum[y1*width+x0]
	bc := lum[y1*width+x]
	br := lum[y1*width+x1]
	gx = (tr - tl) + 2*(mr-ml) + (br - bl)
	gy = (bl - tl) + 2*(bc-tc) + (br - tr)
	return gx, gy
}

// Sobel writes the Sobel gradient magnitude of src into dst. The operator is
// applied to the per-pixel Rec. 601 luminance; the magnitude sqrt(gx^2+gy^2) is
// clamped to [0, 255] and written to the R, G and B channels (a grayscale edge
// map). Alpha is copied from the corresponding source pixel. Edges use
// clamp-to-edge addressing. src and dst are RGBA slices of width*height pixels.
func Sobel(dst, src []uint8, width, height int) {
	lum := lumaPlane(src, width, height)
	forLines(height, width, func(lo, hi int) {
		for y := lo; y < hi; y++ {
			for x := 0; x < width; x++ {
				gx, gy := sobelGradients(lum, width, height, x, y)
				m := ClampByte(math.Sqrt(gx*gx + gy*gy))
				di := (y*width + x) * 4
				dst[di] = m
				dst[di+1] = m
				dst[di+2] = m
				dst[di+3] = src[di+3]
			}
		}
	})
}

// SobelX writes the horizontal Sobel response of src into dst. The signed
// gradient is divided by 8 (the kernel's L1 gain) and offset by 128 so that a
// zero gradient maps to mid-grey, a strong left-to-right rising edge towards
// white and a falling edge towards black; the result is clamped to [0, 255] and
// written to R, G and B. Alpha is preserved. See Sobel for the addressing rules.
func SobelX(dst, src []uint8, width, height int) {
	sobelDirectional(dst, src, width, height, true)
}

// SobelY writes the vertical Sobel response of src into dst, with the same
// scaling and offset convention as SobelX. Alpha is preserved.
func SobelY(dst, src []uint8, width, height int) {
	sobelDirectional(dst, src, width, height, false)
}

// sobelDirectional implements the shared body of SobelX (horizontal=true) and
// SobelY (horizontal=false).
func sobelDirectional(dst, src []uint8, width, height int, horizontal bool) {
	lum := lumaPlane(src, width, height)
	forLines(height, width, func(lo, hi int) {
		for y := lo; y < hi; y++ {
			for x := 0; x < width; x++ {
				gx, gy := sobelGradients(lum, width, height, x, y)
				g := gy
				if horizontal {
					g = gx
				}
				v := ClampByte(g/8 + 128)
				di := (y*width + x) * 4
				dst[di] = v
				dst[di+1] = v
				dst[di+2] = v
				dst[di+3] = src[di+3]
			}
		}
	})
}

// edgeWeights names the three central-difference smoothing triples used by the
// scikit-image edge family. Each operator is a separable 3x3 kernel: a
// derivative [+1, 0, -1] along one axis and a smoothing triple along the other.
// The smoothing triple is normalised so the axis kernel's absolute weights sum
// to one (sobel 0.25/0.5/0.25, prewitt 1/3 each, scharr 0.1875/0.625/0.1875),
// matching skimage.filters.{sobel,prewitt,scharr}. With a 3-tap kernel the
// scipy default boundary mode "reflect" coincides with clamp-to-edge, so the
// library's existing nearest addressing reproduces skimage at the borders.
type edgeWeights struct {
	a, b, c float64 // the smoothing triple (top/bottom for the x-derivative)
}

var (
	sobelSmooth   = edgeWeights{0.25, 0.5, 0.25}
	prewittSmooth = edgeWeights{1.0 / 3, 1.0 / 3, 1.0 / 3}
	scharrSmooth  = edgeWeights{0.1875, 0.625, 0.1875}
)

// edgeGradients computes the horizontal (gx) and vertical (gy) responses of a
// normalised separable edge operator at pixel (x, y) of the width*height
// luminance plane lum, using clamp-to-edge addressing. The operator's x-kernel
// is the outer product of the derivative column [+1, 0, -1] and the smoothing
// row (sm.a, sm.b, sm.c); the y-kernel is its transpose. Luminance is taken in
// [0,255]; the caller scales the result.
func edgeGradients(lum []float64, width, height, x, y int, sm edgeWeights) (gx, gy float64) {
	x0 := clampIndex(x-1, width)
	x1 := clampIndex(x+1, width)
	y0 := clampIndex(y-1, height)
	y1 := clampIndex(y+1, height)
	tl := lum[y0*width+x0]
	tc := lum[y0*width+x]
	tr := lum[y0*width+x1]
	ml := lum[y*width+x0]
	mr := lum[y*width+x1]
	bl := lum[y1*width+x0]
	bc := lum[y1*width+x]
	br := lum[y1*width+x1]
	// x-derivative: (left - right) columns weighted by the smoothing triple
	// across rows. gx = sum over rows of sm * (left - right).
	gx = sm.a*(tl-tr) + sm.b*(ml-mr) + sm.c*(bl-br)
	// y-derivative: (top - bottom) rows weighted by the smoothing triple across
	// columns.
	gy = sm.a*(tl-bl) + sm.b*(tc-bc) + sm.c*(tr-br)
	return gx, gy
}

// edgeMagnitude writes the gradient-magnitude edge map of the named separable
// operator (sobel/prewitt/scharr smoothing triple sm) into dst. It mirrors
// skimage.filters.{prewitt,scharr,sobel} with axis=None: the magnitude is
// sqrt((gx^2 + gy^2)/2) on the luminance scaled to [0,1]; here luminance is in
// [0,255] and the magnitude is written back as a byte (clamped to [0,255]),
// producing a grayscale edge image. Alpha is copied from src. Edges use
// clamp-to-edge addressing (equivalent to skimage's reflect mode for a 3-tap
// kernel). src and dst are RGBA slices of width*height pixels.
func edgeMagnitude(dst, src []uint8, width, height int, sm edgeWeights) {
	lum := lumaPlane(src, width, height)
	forLines(height, width, func(lo, hi int) {
		for y := lo; y < hi; y++ {
			for x := 0; x < width; x++ {
				gx, gy := edgeGradients(lum, width, height, x, y, sm)
				m := ClampByte(math.Sqrt((gx*gx + gy*gy) / 2))
				di := (y*width + x) * 4
				dst[di] = m
				dst[di+1] = m
				dst[di+2] = m
				dst[di+3] = src[di+3]
			}
		}
	})
}

// Prewitt writes the Prewitt gradient-magnitude edge map of src into dst; see
// edgeMagnitude. It matches skimage.filters.prewitt.
func Prewitt(dst, src []uint8, width, height int) {
	edgeMagnitude(dst, src, width, height, prewittSmooth)
}

// Scharr writes the Scharr gradient-magnitude edge map of src into dst; see
// edgeMagnitude. It matches skimage.filters.scharr. The Scharr smoothing triple
// gives the best rotational symmetry of the three operators.
func Scharr(dst, src []uint8, width, height int) {
	edgeMagnitude(dst, src, width, height, scharrSmooth)
}

// SobelMag writes the normalised Sobel gradient-magnitude edge map of src into
// dst using the skimage convention (sqrt((gx^2+gy^2)/2) on luminance in [0,1]).
// This differs from the legacy Sobel above, which uses integer kernels and the
// raw magnitude sqrt(gx^2+gy^2); SobelMag exists so the edge family shares one
// skimage-faithful definition. It matches skimage.filters.sobel.
func SobelMag(dst, src []uint8, width, height int) {
	edgeMagnitude(dst, src, width, height, sobelSmooth)
}

// Laplacian writes the discrete Laplacian edge map of src into dst, matching
// skimage.filters.laplace (ksize=3): the 3x3 kernel
//
//	[ 0 -1  0; -1  4 -1;  0 -1  0 ]
//
// applied to the luminance plane. The signed response is offset by 128 so a
// flat region maps to mid-grey, a bright blob's rim swings above and the centre
// below (or vice versa), clamped to [0,255] and written to R, G and B. Alpha is
// copied from src; edges use clamp-to-edge addressing. The Laplacian is a
// second-derivative operator, so it responds to intensity curvature (lines,
// spots) rather than to step edges.
func Laplacian(dst, src []uint8, width, height int) {
	lum := lumaPlane(src, width, height)
	forLines(height, width, func(lo, hi int) {
		for y := lo; y < hi; y++ {
			for x := 0; x < width; x++ {
				c := lum[y*width+x]
				l := lum[y*width+clampIndex(x-1, width)]
				r := lum[y*width+clampIndex(x+1, width)]
				u := lum[clampIndex(y-1, height)*width+x]
				d := lum[clampIndex(y+1, height)*width+x]
				v := ClampByte(4*c - l - r - u - d + 128)
				di := (y*width + x) * 4
				dst[di] = v
				dst[di+1] = v
				dst[di+2] = v
				dst[di+3] = src[di+3]
			}
		}
	})
}

// Median applies a square median filter of the given radius to src, writing the
// result into dst. Each output channel is the median of the (2*radius+1)^2
// source neighbourhood (computed independently per R, G and B; alpha preserved),
// with clamp-to-edge addressing. It matches scipy.ndimage.median_filter with a
// (2*radius+1)-square footprint and mode="nearest". The window always holds an
// odd number of samples, so the median is the unambiguous middle element.
// Unlike a linear blur, the median removes salt-and-pepper noise while keeping
// edges sharp. dst and src are RGBA slices of width*height pixels; radius >= 1.
func Median(dst, src []uint8, width, height, radius int) {
	win := 2*radius + 1
	count := win * win
	mid := count / 2
	forLines(height, width, func(lo, hi int) {
		// Per-worker scratch holding the window samples for one channel.
		buf := make([]uint8, count)
		for y := lo; y < hi; y++ {
			for x := 0; x < width; x++ {
				di := (y*width + x) * 4
				for c := 0; c < 3; c++ {
					n := 0
					for dy := -radius; dy <= radius; dy++ {
						sy := clampIndex(y+dy, height)
						for dx := -radius; dx <= radius; dx++ {
							sx := clampIndex(x+dx, width)
							buf[n] = src[(sy*width+sx)*4+c]
							n++
						}
					}
					dst[di+c] = medianByte(buf, mid)
				}
				dst[di+3] = src[di+3]
			}
		}
	})
}

// medianByte returns the element of buf that would sit at index mid if buf were
// sorted ascending, using a 256-bin counting selection (the values are bytes).
// This is O(n + 256) per window rather than O(n log n), and leaves buf intact.
func medianByte(buf []uint8, mid int) uint8 {
	var hist [256]int
	for _, v := range buf {
		hist[v]++
	}
	acc := 0
	v := 0
	for ; acc <= mid; v++ {
		acc += hist[v]
	}
	// The loop advances v one past the bin that crossed mid; back up to it. The
	// window count (2*mid+1) guarantees the threshold is crossed at some bin in
	// [0,255], so v is always in range here.
	return uint8(v - 1)
}

// UnsharpMask sharpens src by adding back a scaled high-pass detail layer:
// dst = clamp(src + amount*(src - blurred)), where blurred is the Gaussian blur
// of src (the caller supplies it). The R, G and B channels are processed
// independently and alpha is preserved. This matches skimage.filters.unsharp_mask
// (per channel): the blurred image is gaussian(src, sigma=radius); amount scales
// the recovered detail (0 leaves the image unchanged, larger values sharpen more,
// negative values soften). dst, src and blurred are RGBA slices of equal length.
func UnsharpMask(dst, src, blurred []uint8, amount float64) {
	for i := 0; i < len(src); i += 4 {
		for c := 0; c < 3; c++ {
			s := float64(src[i+c])
			b := float64(blurred[i+c])
			dst[i+c] = ClampByte(s + amount*(s-b))
		}
		dst[i+3] = src[i+3]
	}
}

// Canny detects edges with the Canny algorithm and writes a binary edge map
// (white edges, black elsewhere) into dst. It mirrors the algorithm of
// skimage.feature.canny: the already Gaussian-smoothed luminance plane lum is
// run through the Sobel operator, thinned by non-maximum suppression, and linked
// by hysteresis double-thresholding.
//
// The caller is responsible for the Gaussian pre-smoothing (the public Canny
// applies GaussianBlur with clamp-to-edge borders first); lum is the smoothed
// width*height luminance plane (one float64 per pixel, in [0,255]). lo and hi
// are the absolute magnitude thresholds on the Sobel gradient norm. Borders use
// clamp-to-edge addressing.
//
// Non-maximum suppression uses bilinear interpolation along the gradient
// direction, exactly as skimage documents: the pixel is sorted into one of four
// orientation categories by the signs and relative size of gx and gy, the two
// magnitudes either side of it along the gradient normal are linearly
// interpolated from the neighbouring pixels, and the pixel survives only if its
// magnitude is strictly greater than both. Hysteresis then keeps every
// suppressed pixel at or above hi, plus every pixel at or above lo that is
// 8-connected (transitively) to such a strong pixel.
func Canny(dst []uint8, lum []float64, width, height int, lo, hi float64) {
	n := width * height
	gx := make([]float64, n)
	gy := make([]float64, n)
	mag := make([]float64, n)
	forLines(height, width, func(loY, hiY int) {
		for y := loY; y < hiY; y++ {
			for x := 0; x < width; x++ {
				dx, dy := sobelGradients(lum, width, height, x, y)
				i := y*width + x
				gx[i] = dx
				gy[i] = dy
				mag[i] = math.Sqrt(dx*dx + dy*dy)
			}
		}
	})
	keep := cannySuppress(gx, gy, mag, width, height, lo)
	cannyHysteresis(dst, keep, mag, width, height, hi)
}

// cannySuppress performs bilinear non-maximum suppression: it returns a boolean
// plane marking every pixel that is a local maximum of mag along its gradient
// direction and whose magnitude is >= lo. Border pixels (which lack a full
// neighbourhood) are never kept, matching skimage's masking of the one-pixel
// border.
func cannySuppress(gx, gy, mag []float64, width, height int, lo float64) []bool {
	keep := make([]bool, width*height)
	forLines(height, width, func(loY, hiY int) {
		for y := loY; y < hiY; y++ {
			if y == 0 || y == height-1 {
				continue
			}
			for x := 1; x < width-1; x++ {
				i := y*width + x
				m := mag[i]
				if m < lo || m == 0 {
					continue
				}
				if cannyIsMax(gx[i], gy[i], m, mag, width, x, y) {
					keep[i] = true
				}
			}
		}
	})
	return keep
}

// cannyIsMax reports whether the magnitude m of the pixel at (x,y) is strictly
// greater than the two magnitudes interpolated either side of it along the
// gradient normal. The pixel is classified into one of four octant-pair
// categories by the signs and relative magnitude of (gx,gy); within a category
// the off-axis weight w = min(|gx|,|gy|)/max(|gx|,|gy|) blends the axis-aligned
// neighbour with the diagonal one, exactly as skimage's bilinear NMS does.
func cannyIsMax(dx, dy, m float64, mag []float64, width, x, y int) bool {
	at := func(xx, yy int) float64 { return mag[yy*width+xx] }
	ax, ay := math.Abs(dx), math.Abs(dy)
	var n1, n2 float64
	if ax >= ay {
		// Gradient closer to horizontal: interpolate between the horizontal
		// neighbour and the diagonal one, weighted by ay/ax.
		w := ay / ax
		if dx*dy >= 0 {
			// gx and gy same sign: diagonals are (x+1,y+1) and (x-1,y-1).
			n1 = (1-w)*at(x+1, y) + w*at(x+1, y+1)
			n2 = (1-w)*at(x-1, y) + w*at(x-1, y-1)
		} else {
			n1 = (1-w)*at(x+1, y) + w*at(x+1, y-1)
			n2 = (1-w)*at(x-1, y) + w*at(x-1, y+1)
		}
	} else {
		// Gradient closer to vertical: interpolate between the vertical
		// neighbour and the diagonal one, weighted by ax/ay.
		w := ax / ay
		if dx*dy >= 0 {
			n1 = (1-w)*at(x, y+1) + w*at(x+1, y+1)
			n2 = (1-w)*at(x, y-1) + w*at(x-1, y-1)
		} else {
			n1 = (1-w)*at(x, y+1) + w*at(x-1, y+1)
			n2 = (1-w)*at(x, y-1) + w*at(x+1, y-1)
		}
	}
	return m > n1 && m > n2
}

// cannyHysteresis links the suppressed maxima into the final binary edge map.
// Every kept pixel whose magnitude is >= hi is a confirmed edge and seeds a
// flood fill over 8-connected kept pixels with magnitude >= lo (which the keep
// plane already guarantees), so weak edges survive only when they connect to a
// strong one. dst is written as an RGBA edge map: white (255,255,255,255) on
// edges, opaque black elsewhere.
func cannyHysteresis(dst []uint8, keep []bool, mag []float64, width, height int, hi float64) {
	edge := make([]bool, width*height)
	stack := make([]int, 0, 64)
	for i, k := range keep {
		if k && mag[i] >= hi && !edge[i] {
			edge[i] = true
			stack = append(stack, i)
			// cannySuppress only ever marks strictly-interior pixels (it skips
			// the one-pixel border), so every kept/seed pixel has x in
			// [1,width-2] and y in [1,height-2] and all eight neighbours are
			// valid indices: no bounds check is needed inside the flood fill.
			for len(stack) > 0 {
				p := stack[len(stack)-1]
				stack = stack[:len(stack)-1]
				px, py := p%width, p/width
				for dy := -1; dy <= 1; dy++ {
					ny := py + dy
					for dx := -1; dx <= 1; dx++ {
						q := ny*width + px + dx
						if keep[q] && !edge[q] {
							edge[q] = true
							stack = append(stack, q)
						}
					}
				}
			}
		}
	}
	for i, e := range edge {
		di := i * 4
		var v uint8
		if e {
			v = 255
		}
		dst[di] = v
		dst[di+1] = v
		dst[di+2] = v
		dst[di+3] = 255
	}
}

// morphOp selects the per-window reduction used by the separable morphology
// passes: the minimum (erosion) or the maximum (dilation).
type morphOp bool

const (
	morphMin morphOp = false
	morphMax morphOp = true
)

// Erode applies grayscale erosion (per-channel local minimum over a
// (2*radius+1)-square structuring element) to src, writing the result into dst.
// Dilate applies the corresponding local maximum. Both use clamp-to-edge
// addressing and preserve alpha, and both are separable (a horizontal min/max
// pass followed by a vertical one), matching a square footprint in
// scipy.ndimage.grey_erosion / grey_dilation. dst and src are RGBA slices of
// width*height pixels; radius must be >= 1.
func Erode(dst, src []uint8, width, height, radius int) {
	morph(dst, src, width, height, radius, morphMin)
}

// Dilate applies grayscale dilation; see Erode.
func Dilate(dst, src []uint8, width, height, radius int) {
	morph(dst, src, width, height, radius, morphMax)
}

// morph runs the separable grayscale morphology (erode or dilate) into dst.
//
// Each of the two separable passes (horizontal then vertical) is a 1-D windowed
// min/max of window length 2*radius+1 with clamp-to-edge borders, computed by
// the van Herk / Gil-Werman running extremum (vanHerk1D): exactly three
// comparisons per output pixel independent of the radius, instead of the old
// per-offset fold whose cost scaled with 2*radius+1. min/max is associative and
// commutative, so the windowed result is independent of evaluation order and
// stays bit-identical to the naive square-footprint oracle (matching
// scipy.ndimage.grey_erosion / grey_dilation on a square element). The
// independent rows / columns are still fanned across cores above ParThreshold.
func morph(dst, src []uint8, width, height, radius int, op morphOp) {
	tmp := make([]uint8, len(src))
	// Horizontal pass: src -> tmp (rows are independent).
	forLines(height, width, func(lo, hi int) {
		morphH(tmp, src, width, lo, hi, radius, op)
	})
	// Vertical pass: tmp -> dst (columns are independent; tile by column band).
	forLines(width, height, func(lo, hi int) {
		morphV(dst, tmp, width, height, lo, hi, radius, op)
	})
}

// morphScratch holds the per-worker van Herk scratch buffers, reused across
// every line a worker processes so the hot path allocates nothing. pad holds the
// clamp-padded 1-D signal (length n + 2*radius) and pref / suf the forward
// prefix / backward suffix block extrema over it.
type morphScratch struct {
	pad  []uint8
	pref []uint8
	suf  []uint8
}

// ensure (re)sizes the scratch buffers to hold a padded signal of m elements.
func (s *morphScratch) ensure(m int) {
	if cap(s.pad) < m {
		s.pad = make([]uint8, m)
		s.pref = make([]uint8, m)
		s.suf = make([]uint8, m)
		return
	}
	s.pad = s.pad[:m]
	s.pref = s.pref[:m]
	s.suf = s.suf[:m]
}

// vanHerk1D computes the windowed extremum of the n-sample signal held in
// s.pad[radius : radius+n] over a window of length k = 2*radius+1 with
// clamp-to-edge borders, writing n outputs into out[:n]. The caller must already
// have filled s.pad: the radius leading entries clamped to the first sample, the
// n signal samples, then radius trailing entries clamped to the last sample.
//
// The Gil-Werman scheme partitions the padded signal into blocks of k samples.
// pref holds, within each block, the forward running extremum from the block
// start; suf the backward running extremum to the block end. A window of length
// k aligned at padded index j spans [j, j+k-1], which straddles at most two
// adjacent blocks, so its extremum is op(suf[j], pref[j+k-1]) — three byte
// comparisons per pixel, independent of radius. Output pixel x corresponds to
// the window starting at padded index x (i.e. covering original [x-radius,
// x+radius] after the radius shift).
func (s *morphScratch) vanHerk1D(out []uint8, n, radius int, op morphOp) {
	if n == 0 {
		return
	}
	if op == morphMax {
		vanHerkMax(out, s.pad, s.pref, s.suf, n, radius)
		return
	}
	vanHerkMin(out, s.pad, s.pref, s.suf, n, radius)
}

// vanHerkMax is the O(1)-in-radius running maximum over the clamp-padded signal
// pad (length n+2*radius) using forward block prefix (pref) and backward block
// suffix (suf) extrema; see vanHerk1D. The comparison is expanded inline (no
// func value) so the hot loops stay branch-predictable and inlinable. vanHerkMin
// is the mirror image with the comparison flipped.
func vanHerkMax(out, pad, pref, suf []uint8, n, radius int) {
	k := 2*radius + 1
	m := n + 2*radius
	// Reslice the working arrays to exactly the padded length so the per-block
	// loops and the merge below carry no redundant bounds checks (the compiler
	// proves every index in [0,m)).
	pad = pad[:m]
	pref = pref[:m]
	suf = suf[:m]
	for b := 0; b < m; b += k {
		end := b + k
		if end > m {
			end = m
		}
		acc := pad[b]
		pref[b] = acc
		for i := b + 1; i < end; i++ {
			if v := pad[i]; v > acc {
				acc = v
			}
			pref[i] = acc
		}
		acc = pad[end-1]
		suf[end-1] = acc
		for i := end - 2; i >= b; i-- {
			if v := pad[i]; v > acc {
				acc = v
			}
			suf[i] = acc
		}
	}
	// The merge reads suf[x] and pref[x+k-1] for x in [0,n); both indices stay in
	// [0,m) because n+k-1 = m. Slice pref to [k-1:] so pref[x+k-1] becomes p[x]
	// and out/suf are addressed by the same induction variable, eliminating the
	// bounds checks on the hottest loop.
	out = out[:n]
	suf = suf[:n]
	p := pref[k-1:][:n]
	for x := range out {
		lo := suf[x]
		if hi := p[x]; hi > lo {
			out[x] = hi
		} else {
			out[x] = lo
		}
	}
}

func vanHerkMin(out, pad, pref, suf []uint8, n, radius int) {
	k := 2*radius + 1
	m := n + 2*radius
	pad = pad[:m]
	pref = pref[:m]
	suf = suf[:m]
	for b := 0; b < m; b += k {
		end := b + k
		if end > m {
			end = m
		}
		acc := pad[b]
		pref[b] = acc
		for i := b + 1; i < end; i++ {
			if v := pad[i]; v < acc {
				acc = v
			}
			pref[i] = acc
		}
		acc = pad[end-1]
		suf[end-1] = acc
		for i := end - 2; i >= b; i-- {
			if v := pad[i]; v < acc {
				acc = v
			}
			suf[i] = acc
		}
	}
	out = out[:n]
	suf = suf[:n]
	p := pref[k-1:][:n]
	for x := range out {
		lo := suf[x]
		if hi := p[x]; hi < lo {
			out[x] = hi
		} else {
			out[x] = lo
		}
	}
}

// padClamp fills the radius leading / trailing pad entries from the first / last
// signal sample after the n signal samples have been written into
// s.pad[radius:radius+n].
func (s *morphScratch) padClamp(n, radius int) {
	first := s.pad[radius]
	last := s.pad[radius+n-1]
	for i := 0; i < radius; i++ {
		s.pad[i] = first
		s.pad[radius+n+i] = last
	}
}

// fillPad loads n source samples (read through get) into the signal portion of
// s.pad[radius:radius+n] and clamps the borders. Used by the direct unit tests;
// the production hot paths gather inline to avoid the closure.
func (s *morphScratch) fillPad(n, radius int, get func(i int) uint8) {
	for i := 0; i < n; i++ {
		s.pad[radius+i] = get(i)
	}
	s.padClamp(n, radius)
}

// morphH runs the horizontal van Herk min/max for rows [lo,hi) of an RGBA image,
// one channel at a time. Each row is an independent 1-D signal of width pixels;
// the gather into the padded signal is inlined (no closure) and the three colour
// channels are processed separately through the shared scratch. Alpha is copied
// through.
func morphH(dst, src []uint8, width, lo, hi, radius int, op morphOp) {
	var sc morphScratch
	sc.ensure(width + 2*radius)
	out := make([]uint8, width)
	sig := sc.pad[radius : radius+width]
	for y := lo; y < hi; y++ {
		base := y * width * 4
		for c := 0; c < 3; c++ {
			p := base + c
			for x := 0; x < width; x++ {
				sig[x] = src[p]
				p += 4
			}
			sc.padClamp(width, radius)
			sc.vanHerk1D(out, width, radius, op)
			p = base + c
			for x := 0; x < width; x++ {
				dst[p] = out[x]
				p += 4
			}
		}
		p := base + 3
		for x := 0; x < width; x++ {
			dst[p] = src[p]
			p += 4
		}
	}
}

// morphVTile is the number of columns the vertical pass transposes into a
// contiguous band at a time. Reading a whole band row-by-row turns the otherwise
// stride-(width*4) column gather (one cache line touched per pixel) into mostly
// sequential reads, which dominates the vertical pass cost for large images. A
// small band (8 columns × 3 uint8 planes of height each) keeps the working set
// cache-resident so the gather/scan/scatter all stay fast even at 4096².
const morphVTile = 8

// morphV runs the vertical van Herk min/max for columns [lo,hi). It transposes a
// band of up to morphVTile columns (read sequentially, cache-friendly) into a
// contiguous per-channel buffer, runs the O(1) running extremum down each column
// of the band, and scatters the result back. The three channels are processed
// separately; alpha is copied through.
func morphV(dst, src []uint8, width, height, lo, hi, radius int, op morphOp) {
	var sc morphScratch
	sc.ensure(height + 2*radius)
	sig := sc.pad[radius : radius+height]
	stride := width * 4
	// band[c] holds, transposed, the band's channel c as bw contiguous columns of
	// height samples each: band[c][col*height + y].
	tile := hi - lo
	if tile > morphVTile {
		tile = morphVTile
	}
	var band [3][]uint8
	for c := 0; c < 3; c++ {
		band[c] = make([]uint8, tile*height)
	}
	for x0 := lo; x0 < hi; x0 += morphVTile {
		bw := hi - x0
		if bw > morphVTile {
			bw = morphVTile
		}
		// Transpose-gather the band: sequential pass over the source rows.
		for y := 0; y < height; y++ {
			p := y*stride + x0*4
			off := y
			for j := 0; j < bw; j++ {
				band[0][j*height+off] = src[p]
				band[1][j*height+off] = src[p+1]
				band[2][j*height+off] = src[p+2]
				p += 4
			}
		}
		for j := 0; j < bw; j++ {
			for c := 0; c < 3; c++ {
				col := band[c][j*height : j*height+height]
				copy(sig, col)
				sc.padClamp(height, radius)
				sc.vanHerk1D(col, height, radius, op) // in place: writes back into band
			}
		}
		// Scatter back (sequential pass over the source rows), copying alpha.
		for y := 0; y < height; y++ {
			p := y*stride + x0*4
			off := y
			for j := 0; j < bw; j++ {
				dst[p] = band[0][j*height+off]
				dst[p+1] = band[1][j*height+off]
				dst[p+2] = band[2][j*height+off]
				dst[p+3] = src[p+3]
				p += 4
			}
		}
	}
}

// Histogram returns the 256-bin histogram of the Rec. 601 luminance of src
// (rounded to the nearest integer with ClampByte). src is an RGBA slice.
func Histogram(src []uint8) [256]int {
	var h [256]int
	for i := 0; i < len(src); i += 4 {
		y := ClampByte(0.299*float64(src[i]) + 0.587*float64(src[i+1]) + 0.114*float64(src[i+2]))
		h[y]++
	}
	return h
}

// OtsuThreshold returns the gray level in [0, 255] that maximises the
// between-class variance of the luminance histogram of src (Otsu's method).
// This matches the threshold chosen by skimage.filters.threshold_otsu on the
// 256-bin histogram: pixels with luminance strictly greater than the returned
// value are foreground. For a degenerate single-valued image it returns that
// value.
func OtsuThreshold(src []uint8) uint8 {
	h := Histogram(src)
	total := 0
	var sum float64
	for i, c := range h {
		total += c
		sum += float64(i) * float64(c)
	}
	var sumB float64
	wB := 0
	var maxVar float64
	best := 0
	for t := 0; t < 256; t++ {
		wB += h[t]
		if wB == 0 {
			continue
		}
		wF := total - wB
		if wF == 0 {
			break
		}
		sumB += float64(t) * float64(h[t])
		mB := sumB / float64(wB)
		mF := (sum - sumB) / float64(wF)
		between := float64(wB) * float64(wF) * (mB - mF) * (mB - mF)
		if between > maxVar {
			maxVar = between
			best = t
		}
	}
	return uint8(best)
}

// Threshold binarises src by its Rec. 601 luminance into dst: pixels whose
// luminance is strictly greater than t become white (255,255,255), the rest
// black (0,0,0). Alpha is preserved. dst and src are RGBA slices of equal
// length.
func Threshold(dst, src []uint8, t uint8) {
	for i := 0; i < len(src); i += 4 {
		y := ClampByte(0.299*float64(src[i]) + 0.587*float64(src[i+1]) + 0.114*float64(src[i+2]))
		var v uint8
		if y > t {
			v = 255
		}
		dst[i] = v
		dst[i+1] = v
		dst[i+2] = v
		dst[i+3] = src[i+3]
	}
}

// RGBToHSV converts the R, G, B channels of src to H, S, V, writing each as a
// byte into dst: H is the hue scaled from [0,360) to [0,255] (hue*255/360,
// rounded), S and V are scaled from [0,1] to [0,255]. Alpha is preserved. This
// byte-encoded HSV is a lossy but reversible-within-rounding representation
// convenient for an RGBA-backed pipeline.
func RGBToHSV(dst, src []uint8) {
	for i := 0; i < len(src); i += 4 {
		r := float64(src[i]) / 255
		g := float64(src[i+1]) / 255
		b := float64(src[i+2]) / 255
		max := r
		if g > max {
			max = g
		}
		if b > max {
			max = b
		}
		min := r
		if g < min {
			min = g
		}
		if b < min {
			min = b
		}
		v := max
		delta := max - min
		var s float64
		if max > 0 {
			s = delta / max
		}
		var hue float64
		if delta > 0 {
			switch max {
			case r:
				hue = (g - b) / delta
			case g:
				hue = 2 + (b-r)/delta
			default:
				hue = 4 + (r-g)/delta
			}
			hue *= 60
			if hue < 0 {
				hue += 360
			}
		}
		dst[i] = ClampByte(hue * 255 / 360)
		dst[i+1] = ClampByte(s * 255)
		dst[i+2] = ClampByte(v * 255)
		dst[i+3] = src[i+3]
	}
}

// HSVToRGB is the inverse of RGBToHSV: it interprets the first three channels of
// src as byte-encoded H, S, V (H in [0,255] mapping to [0,360), S and V in
// [0,255] mapping to [0,1]) and writes R, G, B into dst. Alpha is preserved.
func HSVToRGB(dst, src []uint8) {
	for i := 0; i < len(src); i += 4 {
		h := float64(src[i]) / 255 * 360
		s := float64(src[i+1]) / 255
		v := float64(src[i+2]) / 255
		c := v * s
		hp := h / 60
		x := c * (1 - math.Abs(math.Mod(hp, 2)-1))
		var r, g, b float64
		switch int(hp) % 6 {
		case 0:
			r, g, b = c, x, 0
		case 1:
			r, g, b = x, c, 0
		case 2:
			r, g, b = 0, c, x
		case 3:
			r, g, b = 0, x, c
		case 4:
			r, g, b = x, 0, c
		default:
			r, g, b = c, 0, x
		}
		m := v - c
		dst[i] = ClampByte((r + m) * 255)
		dst[i+1] = ClampByte((g + m) * 255)
		dst[i+2] = ClampByte((b + m) * 255)
		dst[i+3] = src[i+3]
	}
}

// FlipH mirrors src left-to-right (column x maps to width-1-x), writing the
// result into dst. Both are RGBA slices of width*height pixels. This matches
// numpy.fliplr on a height-by-width-by-4 array.
func FlipH(dst, src []uint8, width, height int) {
	for y := 0; y < height; y++ {
		row := y * width * 4
		for x := 0; x < width; x++ {
			si := row + x*4
			di := row + (width-1-x)*4
			copyPixel(dst, di, src, si)
		}
	}
}

// FlipV mirrors src top-to-bottom (row y maps to height-1-y), writing the
// result into dst. This matches numpy.flipud.
func FlipV(dst, src []uint8, width, height int) {
	rowBytes := width * 4
	for y := 0; y < height; y++ {
		copy(dst[(height-1-y)*rowBytes:(height-1-y)*rowBytes+rowBytes], src[y*rowBytes:y*rowBytes+rowBytes])
	}
}

// Rotate90 writes src rotated 90 degrees counter-clockwise into dst. The source
// is width*height; the destination is height*width. Source pixel (x, y) maps to
// destination (y, width-1-x), matching numpy.rot90 (k=1).
func Rotate90(dst, src []uint8, width, height int) {
	dstW := height
	for y := 0; y < height; y++ {
		for x := 0; x < width; x++ {
			si := (y*width + x) * 4
			dx := y
			dy := width - 1 - x
			di := (dy*dstW + dx) * 4
			copyPixel(dst, di, src, si)
		}
	}
}

// Rotate180 writes src rotated 180 degrees into dst. Source pixel (x, y) maps to
// destination (width-1-x, height-1-y). Both are width*height.
func Rotate180(dst, src []uint8, width, height int) {
	n := width * height
	for i := 0; i < n; i++ {
		copyPixel(dst, (n-1-i)*4, src, i*4)
	}
}

// Rotate270 writes src rotated 90 degrees clockwise (270 CCW) into dst. The
// source is width*height; the destination is height*width. Source pixel (x, y)
// maps to destination (height-1-y, x), matching numpy.rot90 (k=3).
func Rotate270(dst, src []uint8, width, height int) {
	dstW := height
	for y := 0; y < height; y++ {
		for x := 0; x < width; x++ {
			si := (y*width + x) * 4
			dx := height - 1 - y
			dy := x
			di := (dy*dstW + dx) * 4
			copyPixel(dst, di, src, si)
		}
	}
}

// Crop copies the rectangle of size cw*ch whose top-left corner is at (ox, oy)
// in the width*height source into dst (a cw*ch RGBA slice). The caller is
// responsible for validating that the rectangle lies within the source.
func Crop(dst, src []uint8, width, ox, oy, cw, ch int) {
	for y := 0; y < ch; y++ {
		srcRow := ((oy+y)*width + ox) * 4
		dstRow := (y * cw) * 4
		copy(dst[dstRow:dstRow+cw*4], src[srcRow:srcRow+cw*4])
	}
}

// copyPixel copies the four RGBA bytes at src[si:] into dst[di:].
func copyPixel(dst []uint8, di int, src []uint8, si int) {
	dst[di] = src[si]
	dst[di+1] = src[si+1]
	dst[di+2] = src[si+2]
	dst[di+3] = src[si+3]
}

// ResizeNearest scales a width*height source image into a dstW*dstH destination
// using nearest-neighbour sampling.
func ResizeNearest(dst, src []uint8, srcW, srcH, dstW, dstH int) {
	for y := 0; y < dstH; y++ {
		sy := y * srcH / dstH
		for x := 0; x < dstW; x++ {
			sx := x * srcW / dstW
			si := (sy*srcW + sx) * 4
			di := (y*dstW + x) * 4
			dst[di] = src[si]
			dst[di+1] = src[si+1]
			dst[di+2] = src[si+2]
			dst[di+3] = src[si+3]
		}
	}
}

// ResizeBilinear scales a width*height source image into a dstW*dstH
// destination using bilinear interpolation. Sample positions use the centre of
// each destination pixel mapped back into source space.
func ResizeBilinear(dst, src []uint8, srcW, srcH, dstW, dstH int) {
	scaleX := float64(srcW) / float64(dstW)
	scaleY := float64(srcH) / float64(dstH)
	for y := 0; y < dstH; y++ {
		fy := (float64(y)+0.5)*scaleY - 0.5
		y0 := int(math.Floor(fy))
		wy := fy - float64(y0)
		y0c := clampIndex(y0, srcH)
		y1c := clampIndex(y0+1, srcH)
		for x := 0; x < dstW; x++ {
			fx := (float64(x)+0.5)*scaleX - 0.5
			x0 := int(math.Floor(fx))
			wx := fx - float64(x0)
			x0c := clampIndex(x0, srcW)
			x1c := clampIndex(x0+1, srcW)
			i00 := (y0c*srcW + x0c) * 4
			i01 := (y0c*srcW + x1c) * 4
			i10 := (y1c*srcW + x0c) * 4
			i11 := (y1c*srcW + x1c) * 4
			di := (y*dstW + x) * 4
			for c := 0; c < 4; c++ {
				top := float64(src[i00+c])*(1-wx) + float64(src[i01+c])*wx
				bot := float64(src[i10+c])*(1-wx) + float64(src[i11+c])*wx
				dst[di+c] = ClampByte(top*(1-wy) + bot*wy)
			}
		}
	}
}
