package kernels

// amd64: SSE2 float64 multiply-accumulate and min/max kernels generated by
// go-asmgen (simd_amd64.s). SSE2 is part of the amd64 baseline (GOAMD64=v1), so
// the kernels are always callable — there is no CPU-feature branch.
//
//go:generate sh -c "cd asmgen/amd64 && GOWORK=off GOFLAGS=-mod=mod go run gen.go && mv simd_amd64.s ../../simd_amd64.s"

// HaveSIMD reports that this build ships SIMD separable kernels, so the dispatch
// wrappers route the Gaussian and morphology inner loops through them. The
// per-arch CI execution job validates each against its scalar oracle.
const HaveSIMD = true

// SIMDName identifies the vector kernel family for the per-arch test log.
const SIMDName = "SSE2"

// axpy computes dst[i] += a*src[i] over the whole pair of slices, which must be
// the same non-zero length, via the SSE2 kernel.
func axpy(dst, src []float64, a float64) {
	if len(dst) == 0 {
		return
	}
	axpySSE2(&dst[0], &src[0], a, len(dst))
}

// vminInto / vmaxInto compute dst[i] = min/max(dst[i], src[i]) over the whole
// pair of slices via the SSE2 kernels.
func vminInto(dst, src []float64) {
	if len(dst) == 0 {
		return
	}
	vminSSE2(&dst[0], &src[0], len(dst))
}

func vmaxInto(dst, src []float64) {
	if len(dst) == 0 {
		return
	}
	vmaxSSE2(&dst[0], &src[0], len(dst))
}

//go:noescape
func axpySSE2(dst, src *float64, a float64, n int)

//go:noescape
func vminSSE2(dst, src *float64, n int)

//go:noescape
func vmaxSSE2(dst, src *float64, n int)
