// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·axpyNEON(SB), NOSPLIT, $0-32
	MOVD dst+0(FP), R0
	MOVD src+8(FP), R1
	FMOVD a+16(FP), F8
	MOVD n+24(FP), R2
	FMOVD F8, R3
	VDUP R3, V16.D2
	block:
	CMP $4, R2
	BLT tail
	VLD1 (R1), [V0.D2, V1.D2]
	VLD1 (R0), [V2.D2, V3.D2]
	VFMLA V0.D2, V16.D2, V2.D2
	VFMLA V1.D2, V16.D2, V3.D2
	VST1 [V2.D2, V3.D2], (R0)
	ADD $32, R0, R0
	ADD $32, R1, R1
	SUB $4, R2
	B block
	tail:
	CBZ R2, done
	FMOVD.P 8(R1), F1
	FMOVD (R0), F2
	FMADDD F8, F2, F1, F2
	FMOVD.P F2, 8(R0)
	SUB $1, R2
	B tail
	done:
	RET

TEXT ·vminNEON(SB), NOSPLIT, $0-24
	MOVD dst+0(FP), R0
	MOVD src+8(FP), R1
	MOVD n+16(FP), R2
	block:
	CMP $4, R2
	BLT tail
	VLD1 (R0), [V0.D2, V1.D2]
	VLD1 (R1), [V2.D2, V3.D2]
	WORD $0x4EE2F400
	WORD $0x4EE3F421
	VST1 [V0.D2, V1.D2], (R0)
	ADD $32, R0, R0
	ADD $32, R1, R1
	SUB $4, R2
	B block
	tail:
	CBZ R2, done
	FMOVD (R0), F0
	FMOVD.P 8(R1), F1
	FMIND F1, F0, F0
	FMOVD.P F0, 8(R0)
	SUB $1, R2
	B tail
	done:
	RET

TEXT ·vmaxNEON(SB), NOSPLIT, $0-24
	MOVD dst+0(FP), R0
	MOVD src+8(FP), R1
	MOVD n+16(FP), R2
	block:
	CMP $4, R2
	BLT tail
	VLD1 (R0), [V0.D2, V1.D2]
	VLD1 (R1), [V2.D2, V3.D2]
	WORD $0x4E62F400
	WORD $0x4E63F421
	VST1 [V0.D2, V1.D2], (R0)
	ADD $32, R0, R0
	ADD $32, R1, R1
	SUB $4, R2
	B block
	tail:
	CBZ R2, done
	FMOVD (R0), F0
	FMOVD.P 8(R1), F1
	FMAXD F1, F0, F0
	FMOVD.P F0, 8(R0)
	SUB $1, R2
	B tail
	done:
	RET

