package kernels

// arm64: NEON float64 multiply-accumulate and min/max kernels generated by
// go-asmgen (simd_arm64.s). NEON (ASIMD) is part of the arm64 baseline the Go
// toolchain requires, so the kernels are always callable — there is no
// CPU-feature branch.
//
//go:generate sh -c "cd asmgen/arm64 && GOWORK=off GOFLAGS=-mod=mod go run gen.go && mv simd_arm64.s ../../simd_arm64.s"

// HaveSIMD reports that this build ships SIMD separable kernels.
const HaveSIMD = true

// SIMDName identifies the vector kernel family for the per-arch test log.
const SIMDName = "NEON"

// axpy computes dst[i] += a*src[i] over the whole pair of slices (same non-zero
// length) via the NEON kernel; bit-identical to the scalar oracle (arm64 fuses
// the scalar form to FMADDD, which VFMLA reproduces).
func axpy(dst, src []float64, a float64) {
	if len(dst) == 0 {
		return
	}
	axpyNEON(&dst[0], &src[0], a, len(dst))
}

// vminInto / vmaxInto compute dst[i] = min/max(dst[i], src[i]) over the whole
// pair of slices via the NEON kernels.
func vminInto(dst, src []float64) {
	if len(dst) == 0 {
		return
	}
	vminNEON(&dst[0], &src[0], len(dst))
}

func vmaxInto(dst, src []float64) {
	if len(dst) == 0 {
		return
	}
	vmaxNEON(&dst[0], &src[0], len(dst))
}

//go:noescape
func axpyNEON(dst, src *float64, a float64, n int)

//go:noescape
func vminNEON(dst, src *float64, n int)

//go:noescape
func vmaxNEON(dst, src *float64, n int)
