// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·axpyVX(SB), NOSPLIT, $0-32
	MOVD dst+0(FP), R1
	MOVD src+8(FP), R2
	FMOVD a+16(FP), F0
	MOVD n+24(FP), R3
	VLREPG a+16(FP), V3
	block:
	CMPBLT R3, $2, tail
	VL (R2), V1
	VL (R1), V2
	VFMADB V1, V3, V2, V2
	VST V2, (R1)
	ADD $16, R1
	ADD $16, R2
	SUB $2, R3
	BR block
	tail:
	CMPBEQ R3, $0, done
	FMOVD (R2), F1
	FMOVD (R1), F2
	FMADD F0, F1, F2
	FMOVD F2, (R1)
	done:
	RET

TEXT ·vminVX(SB), NOSPLIT, $0-24
	MOVD dst+0(FP), R1
	MOVD src+8(FP), R2
	MOVD n+16(FP), R3
	block:
	CMPBLT R3, $2, tail
	VL (R1), V0
	VL (R2), V1
	VFMINDB $1, V1, V0, V0
	VST V0, (R1)
	ADD $16, R1
	ADD $16, R2
	SUB $2, R3
	BR block
	tail:
	CMPBEQ R3, $0, done
	FMOVD (R1), F0
	FMOVD (R2), F1
	WFMINDB $1, V1, V0, V0
	FMOVD F0, (R1)
	done:
	RET

TEXT ·vmaxVX(SB), NOSPLIT, $0-24
	MOVD dst+0(FP), R1
	MOVD src+8(FP), R2
	MOVD n+16(FP), R3
	block:
	CMPBLT R3, $2, tail
	VL (R1), V0
	VL (R2), V1
	VFMAXDB $1, V1, V0, V0
	VST V0, (R1)
	ADD $16, R1
	ADD $16, R2
	SUB $2, R3
	BR block
	tail:
	CMPBEQ R3, $0, done
	FMOVD (R1), F0
	FMOVD (R2), F1
	WFMAXDB $1, V1, V0, V0
	FMOVD F0, (R1)
	done:
	RET

